name: Format Check

on:
  push:
    branches: main
    paths:
      - '.github/workflows/format_check.yml'
      - '**.jl'
  pull_request:
    branches: main
    paths:
      - '.github/workflows/format_check.yml'
      - '**.jl'
jobs:
  format_check: 
    uses: ProjectTorreyPines/GitHubActionsWorkflows/.github/workflows/format_check.yml@master