name: Make Docs
on:
  push:
    branches: main
    paths:
      - '.github/workflows/make_docs.yml'
      - 'src/**'
      - 'docs/**'
    tags: '*'
  pull_request:
    branches: main
    paths:
      - '.github/workflows/make_docs.yml'
      - 'src/**'
      - 'docs/**'
  workflow_dispatch:
    
jobs:
  make_docs:
    name: Documentation
    permissions:
      actions: write
      contents: write
      statuses: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.x]
        julia-arch: [x64]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
      - uses: julia-actions/cache@v2
      - name: Install dependencies, build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        run: |
          julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'; julia --project=docs/ docs/make.jl