name: TagBot
on:
  issue_comment:
    types:
      - created
  workflow_dispatch:
    inputs:
      lookback:
        default: "3"
jobs:
  TagBot:
    uses: ProjectTorreyPines/GitHubActionsWorkflows/.github/workflows/tag_bot.yml@master
    secrets: inherit
    # This action uses JuliaRegistries/TagBot to tag the registered version on Github.
