name: Test

on:
  push:
    branches: main
    paths:
      - '.github/workflows/test.yml'
      - 'src/**'
      - 'test/**'
      - 'Project.toml'
  pull_request:
    branches: main
    paths:
      - '.github/workflows/test.yml'
      - 'src/**'
      - 'test/**'
      - 'Project.toml'

jobs:
  test:
    name: Test
    permissions:
      actions: write
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.x]
        julia-arch: [x64]
        os: [ubuntu-latest, macOS-latest]
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: actions/checkout@v4
      - name: Add SSH keys
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_KEY }}
      - name: Configure ssh
        run: |
          echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-runtest@v1
      - name: 'Process Coverage'
        uses: julia-actions/julia-processcoverage@v1
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
